name: BaguettePlugin
version: '1.0-SNAPSHOT'
main: com.baguette.smp.BaguettePlugin
api-version: '1.20'
commands:
  boost:
    description: Mmmh des effect ??
    usage: /boost
    permission: BaguettePlugin.boost

  mesboosts:
    description: Mmmh Mes effect ??
    usage: /mesboosts
    permission: BaguettePlugin.mesboosts
